# Apple Global Sales

In [1]:
import numpy as np
import pandas as pd
pd.set_option('display.max_columns', None)
import plotly.express as px
import streamlit as st

In [2]:
df = pd.read_csv('../Data/Raw Data/apple_global_sales_dataset.csv')

In [3]:
df

,sale_id,sale_date,year,quarter,month,country,region,city,product_name,category,storage,color,unit_price_usd,discount_pct,units_sold,discounted_price_usd,revenue_usd,currency,fx_rate_to_usd,revenue_local_currency,sales_channel,payment_method,customer_segment,customer_age_group,previous_device_os,customer_rating,return_status
0,APPL-00000001,2022-01-03,2022,Q1,January,Argentina,South America,Buenos Aires,AirPods (3rd Gen),AirPods,NaN,Starlight,159.27,7,1,148.12,148.12,ARS,907.0,1.343448e+05,Third-Party Retailer,Cash,Government,45–54,NaN,4.1,Kept
1,APPL-00000002,2022-01-04,2022,Q1,January,Argentina,South America,Buenos Aires,USB-C Woven Charge Cable,Accessories,NaN,Black,29.99,15,5,25.49,127.45,ARS,907.0,1.155971e+05,Authorized Reseller,Debit Card,Business,45–54,NaN,4.8,Kept
2,APPL-00000003,2022-05-18,2022,Q2,May,Argentina,South America,Buenos Aires,Apple Watch Series 8,Apple Watch,NaN,Titanium,293.92,0,4,293.92,1175.68,ARS,907.0,1.066342e+06,Corporate / B2B,Credit Card,Individual,18–24,NaN,4.3,Kept
3,APPL-00000004,2022-05-23,2022,Q2,May,Argentina,South America,Buenos Aires,MacBook Pro 14-inch (M3),Mac,1 TB SSD,Starlight,1932.77,0,2,1932.77,3865.54,ARS,907.0,3.506045e+06,Carrier Store,Credit Card,Education,45–54,NaN,NaN,Kept
4,APPL-00000005,2022-07-13,2022,Q3,July,Argentina,South America,Buenos Aires,Apple Watch Ultra 2,Apple Watch,NaN,Midnight,755.44,5,3,717.67,2153.01,ARS,907.0,1.952780e+06,Apple Store,Net Banking,Education,18–24,NaN,NaN,Kept
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11495,APPL-00011496,2024-02-08,2024,Q1,February,Vietnam,Asia,Nha Trang,Apple Watch Series 9,Apple Watch,NaN,Natural,420.53,5,2,399.50,799.00,VND,24500.0,1.957550e+07,Third-Party Retailer,Gift Card,Individual,18–24,NaN,4.0,Kept
11496,APPL-00011497,2024-02-15,2024,Q1,February,Vietnam,Asia,Nha Trang,Mac Pro (M2 Ultra),Mac,256 GB SSD,Midnight,7302.60,7,1,6791.42,6791.42,VND,24500.0,1.663898e+08,Corporate / B2B,Gift Card,Education,45–54,NaN,4.9,Kept
11497,APPL-00011498,2024-08-28,2024,Q3,August,Vietnam,Asia,Nha Trang,iPhone 15,iPhone,128 GB,Deep Purple,759.97,7,5,706.77,3533.85,VND,24500.0,8.657932e+07,Authorized Reseller,Debit Card,Government,35–44,iOS 16,3.8,Kept
11498,APPL-00011499,2024-08-31,2024,Q3,August,Vietnam,Asia,Nha Trang,iPhone SE (3rd Gen),iPhone,512 GB,Black,438.99,0,1,438.99,438.99,VND,24500.0,1.075526e+07,Apple Store,EMI / Installment,Education,55+,iOS 17,NaN,Kept
11499,APPL-00011500,2024-10-10,2024,Q4,October,Vietnam,Asia,Nha Trang,iPhone 15 Pro Max,iPhone,512 GB,Silver,1271.57,7,1,1182.56,1182.56,VND,24500.0,2.897272e+07,Online (Apple.com),EMI / Installment,Individual,35–44,Other,3.6,Kept

In [4]:
df.columns

Index(['sale_id', 'sale_date', 'year', 'quarter', 'month', 'country', 'region',
       'city', 'product_name', 'category', 'storage', 'color',
       'unit_price_usd', 'discount_pct', 'units_sold', 'discounted_price_usd',
       'revenue_usd', 'currency', 'fx_rate_to_usd', 'revenue_local_currency',
       'sales_channel', 'payment_method', 'customer_segment',
       'customer_age_group', 'previous_device_os', 'customer_rating',
       'return_status'],
      dtype='object')

In [5]:
df['sale_id'].unique()

array(['APPL-00000001', 'APPL-00000002', 'APPL-00000003', ...,
       'APPL-00011498', 'APPL-00011499', 'APPL-00011500'],
      shape=(11500,), dtype=object)

In [6]:
df['sale_id'].nunique()

11500

In [7]:
df['sale_id'].isna().sum()

np.int64(0)

## Sales Time Columns

In [8]:
df['sale_date'].unique()

array(['2022-01-03', '2022-01-04', '2022-05-18', ..., '2024-04-06',
       '2024-03-13', '2024-08-12'], shape=(1096,), dtype=object)

In [9]:
df['sale_date'].nunique()

1096

In [10]:
df['sale_date'].isna().sum()

np.int64(0)

In [11]:
df['sale_date'].astype('date32[pyarrow]')

0        2022-01-03
1        2022-01-04
2        2022-05-18
3        2022-05-23
4        2022-07-13
            ...
11495    2024-02-08
11496    2024-02-15
11497    2024-08-28
11498    2024-08-31
11499    2024-10-10
Name: sale_date, Length: 11500, dtype: date32[day][pyarrow]

In [12]:
df['year'].unique()

array([2022, 2023, 2024])

In [13]:
df['year'].dtype

dtype('int64')

In [14]:
df['quarter'].unique()

array(['Q1', 'Q2', 'Q3', 'Q4'], dtype=object)

In [15]:
df['month'].unique()

array(['January', 'May', 'July', 'August', 'February', 'March', 'April',
       'September', 'November', 'June', 'October', 'December'],
      dtype=object)

In [16]:
df.sample()

,sale_id,sale_date,year,quarter,month,country,region,city,product_name,category,storage,color,unit_price_usd,discount_pct,units_sold,discounted_price_usd,revenue_usd,currency,fx_rate_to_usd,revenue_local_currency,sales_channel,payment_method,customer_segment,customer_age_group,previous_device_os,customer_rating,return_status
2548,APPL-00002549,2022-09-07,2022,Q3,September,Denmark,Europe,Kolding,Mac mini (M2),Mac,256 GB SSD,Midnight,581.36,5,5,552.29,2761.45,DKK,6.9,19054.01,Corporate / B2B,Net Banking,Business,18–24,NaN,3.2,Kept

## Sales Location Columns

In [17]:
df.columns

Index(['sale_id', 'sale_date', 'year', 'quarter', 'month', 'country', 'region',
       'city', 'product_name', 'category', 'storage', 'color',
       'unit_price_usd', 'discount_pct', 'units_sold', 'discounted_price_usd',
       'revenue_usd', 'currency', 'fx_rate_to_usd', 'revenue_local_currency',
       'sales_channel', 'payment_method', 'customer_segment',
       'customer_age_group', 'previous_device_os', 'customer_rating',
       'return_status'],
      dtype='object')

In [18]:
df['country'].unique()

array(['Argentina', 'Australia', 'Austria', 'Bangladesh', 'Belgium',
       'Brazil', 'Canada', 'Chile', 'China', 'Colombia', 'Denmark',
       'Egypt', 'Finland', 'France', 'Germany', 'Hong Kong', 'India',
       'Indonesia', 'Ireland', 'Italy', 'Japan', 'Kenya', 'Malaysia',
       'Mexico', 'Netherlands', 'New Zealand', 'Nigeria', 'Norway',
       'Pakistan', 'Philippines', 'Poland', 'Portugal', 'Russia',
       'Saudi Arabia', 'Singapore', 'South Africa', 'South Korea',
       'Spain', 'Sweden', 'Switzerland', 'Taiwan', 'Thailand', 'Turkey',
       'UAE', 'United Kingdom', 'United States', 'Vietnam'], dtype=object)

In [19]:
df['country'].isna().sum()

np.int64(0)

In [20]:
df['region'].unique()

array(['South America', 'Oceania', 'Europe', 'Asia', 'North America',
       'Africa', 'Europe/Asia', 'Middle East'], dtype=object)

In [21]:
df[df['region']=='Europe/Asia']

,sale_id,sale_date,year,quarter,month,country,region,city,product_name,category,storage,color,unit_price_usd,discount_pct,units_sold,discounted_price_usd,revenue_usd,currency,fx_rate_to_usd,revenue_local_currency,sales_channel,payment_method,customer_segment,customer_age_group,previous_device_os,customer_rating,return_status
7858,APPL-00007859,2022-01-11,2022,Q1,January,Russia,Europe/Asia,Chelyabinsk,Magic Trackpad,Accessories,NaN,Silver,137.25,0,3,137.25,411.75,RUB,91.5,37675.12,Third-Party Retailer,Gift Card,Individual,18–24,NaN,NaN,Kept
7859,APPL-00007860,2022-02-24,2022,Q1,February,Russia,Europe/Asia,Chelyabinsk,Apple Watch Ultra 2,Apple Watch,NaN,Titanium,772.77,5,1,734.13,734.13,RUB,91.5,67172.90,Apple Store,Gift Card,Business,55+,NaN,4.1,Kept
7860,APPL-00007861,2022-03-07,2022,Q1,March,Russia,Europe/Asia,Chelyabinsk,iPhone 13 Pro Max,iPhone,512 GB,White Titanium,1129.30,0,3,1129.30,3387.90,RUB,91.5,309992.85,Authorized Reseller,Gift Card,Individual,25–34,Android,4.4,Returned
7861,APPL-00007862,2022-04-01,2022,Q2,April,Russia,Europe/Asia,Chelyabinsk,AirPods Max,AirPods,NaN,Midnight,530.72,15,1,451.11,451.11,RUB,91.5,41276.57,Authorized Reseller,Credit Card,Business,18–24,NaN,NaN,Kept
7862,APPL-00007863,2022-04-15,2022,Q2,April,Russia,Europe/Asia,Chelyabinsk,iPhone 15 Pro,iPhone,256 GB,Yellow,966.03,0,1,966.03,966.03,RUB,91.5,88391.74,Corporate / B2B,EMI / Installment,Education,25–34,iOS 15,4.2,Kept
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10556,APPL-00010557,2024-01-27,2024,Q1,January,Turkey,Europe/Asia,Mersin,iPhone 14 Pro,iPhone,1 TB,Deep Purple,926.95,2,2,908.41,1816.82,TRY,30.5,55413.01,Online (Apple.com),Credit Card,Business,35–44,Other,NaN,Kept
10557,APPL-00010558,2024-02-25,2024,Q1,February,Turkey,Europe/Asia,Mersin,Apple Watch Ultra 2,Apple Watch,NaN,Natural,839.56,5,1,797.58,797.58,TRY,30.5,24326.19,Carrier Store,EMI / Installment,Education,55+,NaN,4.2,Kept
10558,APPL-00010559,2024-03-16,2024,Q1,March,Turkey,Europe/Asia,Mersin,iPad Pro 12.9-inch (M2),iPad,128 GB,Starlight,1161.89,0,3,1161.89,3485.67,TRY,30.5,106312.93,Carrier Store,Debit Card,Individual,45–54,NaN,4.3,Kept
10559,APPL-00010560,2024-07-01,2024,Q3,July,Turkey,Europe/Asia,Mersin,iPhone 13 Mini,iPhone,128 GB,Black Titanium,556.95,0,2,556.95,1113.90,TRY,30.5,33973.95,Authorized Reseller,Debit Card,Education,18–24,Android,3.2,Kept
10560,APPL-00010561,2024-10-07,2024,Q4,October,Turkey,Europe/Asia,Mersin,USB-C Woven Charge Cable,Accessories,NaN,Silver,29.65,3,2,28.76,57.52,TRY,30.5,1754.36,Apple Store,Net Banking,Government,45–54,NaN,3.2,Kept

In [22]:
df['city'].isna().sum()

np.int64(0)

## Sales Product Columns

In [23]:
df.columns

Index(['sale_id', 'sale_date', 'year', 'quarter', 'month', 'country', 'region',
       'city', 'product_name', 'category', 'storage', 'color',
       'unit_price_usd', 'discount_pct', 'units_sold', 'discounted_price_usd',
       'revenue_usd', 'currency', 'fx_rate_to_usd', 'revenue_local_currency',
       'sales_channel', 'payment_method', 'customer_segment',
       'customer_age_group', 'previous_device_os', 'customer_rating',
       'return_status'],
      dtype='object')

In [24]:
df['product_name'].unique()

array(['AirPods (3rd Gen)', 'USB-C Woven Charge Cable',
       'Apple Watch Series 8', 'MacBook Pro 14-inch (M3)',
       'Apple Watch Ultra 2', 'Magic Keyboard', 'iPhone 15 Pro Max',
       'Apple TV 4K (3rd Gen)', 'iPad Mini (6th Gen)',
       'iPad (10th Generation)', 'iPad Pro 12.9-inch (M2)',
       'iPhone 15 Pro', 'iPhone 15 Plus', 'iPhone 13 Pro',
       'MacBook Air 13-inch (M2)', 'iPad Pro 11-inch (M2)',
       'Apple Pencil (2nd Gen)', 'iPad Air (M1)', 'iPhone SE (3rd Gen)',
       'Magic Mouse', 'AirPods Pro (2nd Gen)', 'iPhone 14',
       'iPhone 13 Mini', 'iPhone 15', 'MacBook Air 15-inch (M2)',
       'MagSafe Charger', 'iPhone 13', 'iPhone 14 Plus', 'Mac mini (M2)',
       'Apple Watch SE (2nd Gen)', 'Apple Pencil (1st Gen)',
       'AirPods (2nd Gen)', 'Magic Trackpad', 'iPhone 13 Pro Max',
       'MacBook Pro 16-inch (M3 Pro)', 'AirPods Max', 'HomePod mini',
       'iPhone 14 Pro Max', 'Apple Watch Series 9', 'Mac Pro (M2 Ultra)',
       'iPhone 14 Pro', 'HomePod (2nd Gen)', 'iMac 24-inch (M3)'],
      dtype=object)

In [25]:
df['product_name'].isna().sum()

np.int64(0)

In [26]:
df['category'].unique()

array(['AirPods', 'Accessories', 'Apple Watch', 'Mac', 'iPhone', 'iPad'],
      dtype=object)

In [27]:
df['storage'].unique()

array([nan, '1 TB SSD', '64 GB', '128 GB', '256 GB', '1 TB', '2 TB SSD',
       '512 GB', '512 GB SSD', '2 TB', '256 GB SSD'], dtype=object)

In [28]:
df['storage'].fillna('Not Applicable',inplace=True)

C:\Users\Majid Mokhtar\AppData\Local\Temp\ipykernel_12428\4122581186.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['storage'].fillna('Not Applicable',inplace=True)

In [29]:
df['storage'].unique()

array(['Not Applicable', '1 TB SSD', '64 GB', '128 GB', '256 GB', '1 TB',
       '2 TB SSD', '512 GB', '512 GB SSD', '2 TB', '256 GB SSD'],
      dtype=object)

In [30]:
df['color'].unique()

array(['Starlight', 'Black', 'Titanium', 'Midnight', 'Silver', 'White',
       'Space Gray', 'Black Titanium', 'Blue', 'Blue Titanium', 'Purple',
       'Sky', 'Product Red', 'Deep Purple', 'Gold', 'Yellow', 'Natural',
       'Natural Titanium', 'Green', 'White Titanium'], dtype=object)

## Sales Numbers Columns

In [31]:
df.columns

Index(['sale_id', 'sale_date', 'year', 'quarter', 'month', 'country', 'region',
       'city', 'product_name', 'category', 'storage', 'color',
       'unit_price_usd', 'discount_pct', 'units_sold', 'discounted_price_usd',
       'revenue_usd', 'currency', 'fx_rate_to_usd', 'revenue_local_currency',
       'sales_channel', 'payment_method', 'customer_segment',
       'customer_age_group', 'previous_device_os', 'customer_rating',
       'return_status'],
      dtype='object')

In [32]:
df['unit_price_usd'].unique()

array([ 159.27,   29.99,  293.92, ...,  759.97,  438.99, 1271.57],
      shape=(10616,))

In [33]:
df['unit_price_usd'].isna().sum()

np.int64(0)

In [34]:
df['unit_price_usd'].dtype

dtype('float64')

In [35]:
df['discount_pct'].unique()

array([ 7, 15,  0,  5,  3,  2, 10])

In [36]:
df['discount_pct'].dtype

dtype('int64')

In [37]:
df['units_sold'].unique()

array([1, 5, 4, 2, 3, 8, 7, 6])

In [38]:
df['units_sold'].dtype

dtype('int64')

In [39]:
df['discounted_price_usd'].unique()

array([ 148.12,   25.49,  293.92, ...,  706.77,  438.99, 1182.56],
      shape=(10787,))

In [40]:
df['discounted_price_usd'].isna().sum()

np.int64(0)

In [41]:
df['discounted_price_usd'].dtype

dtype('float64')

In [42]:
df['units_sold'].unique()

array([1, 5, 4, 2, 3, 8, 7, 6])

In [43]:
df['discounted_price_usd'].unique()

array([ 148.12,   25.49,  293.92, ...,  706.77,  438.99, 1182.56],
      shape=(10787,))

In [44]:
df['discounted_price_usd'].isna().sum()

np.int64(0)

In [45]:
df['discounted_price_usd'].dtype

dtype('float64')

In [46]:
df['revenue_usd'].unique()

array([ 148.12,  127.45, 1175.68, ..., 3533.85,  438.99, 1182.56],
      shape=(11142,))

In [47]:
df['revenue_usd'].isna().sum()

np.int64(0)

In [48]:
df['revenue_usd'].dtype

dtype('float64')

In [49]:
df['currency'].unique()

array(['ARS', 'AUD', 'EUR', 'BDT', 'BRL', 'CAD', 'CLP', 'CNY', 'COP',
       'DKK', 'EGP', 'HKD', 'INR', 'IDR', 'JPY', 'KES', 'MYR', 'MXN',
       'NZD', 'NGN', 'NOK', 'PKR', 'PHP', 'PLN', 'RUB', 'SAR', 'SGD',
       'ZAR', 'KRW', 'SEK', 'CHF', 'TWD', 'THB', 'TRY', 'AED', 'GBP',
       'USD', 'VND'], dtype=object)

In [50]:
df['fx_rate_to_usd'].unique()

array([9.070e+02, 1.530e+00, 9.200e-01, 1.100e+02, 4.970e+00, 1.360e+00,
       9.600e+02, 7.240e+00, 3.960e+03, 6.900e+00, 3.090e+01, 7.820e+00,
       8.350e+01, 1.570e+04, 1.498e+02, 1.290e+02, 4.710e+00, 1.715e+01,
       1.630e+00, 1.550e+03, 1.065e+01, 2.790e+02, 5.650e+01, 3.970e+00,
       9.150e+01, 3.750e+00, 1.340e+00, 1.890e+01, 1.328e+03, 1.055e+01,
       8.800e-01, 3.180e+01, 3.520e+01, 3.050e+01, 3.670e+00, 7.900e-01,
       1.000e+00, 2.450e+04])

In [51]:
df['fx_rate_to_usd'].dtype

dtype('float64')

In [52]:
df['revenue_local_currency'].unique()

array([  134344.84,   115597.15,  1066341.76, ..., 86579325.  ,
       10755255.  , 28972720.  ], shape=(11445,))

In [53]:
df['revenue_local_currency'].isna().sum()

np.int64(0)

In [54]:
df['revenue_local_currency'].dtype

dtype('float64')

## Sales Customers Columns

In [55]:
df.columns

Index(['sale_id', 'sale_date', 'year', 'quarter', 'month', 'country', 'region',
       'city', 'product_name', 'category', 'storage', 'color',
       'unit_price_usd', 'discount_pct', 'units_sold', 'discounted_price_usd',
       'revenue_usd', 'currency', 'fx_rate_to_usd', 'revenue_local_currency',
       'sales_channel', 'payment_method', 'customer_segment',
       'customer_age_group', 'previous_device_os', 'customer_rating',
       'return_status'],
      dtype='object')

In [56]:
df['sales_channel'].unique()

array(['Third-Party Retailer', 'Authorized Reseller', 'Corporate / B2B',
       'Carrier Store', 'Apple Store', 'Online (Apple.com)'], dtype=object)

In [57]:
df['payment_method'].unique()

array(['Cash', 'Debit Card', 'Credit Card', 'Net Banking', 'Gift Card',
       'Apple Pay', 'EMI / Installment'], dtype=object)

In [58]:
df['customer_segment'].unique()

array(['Government', 'Business', 'Individual', 'Education'], dtype=object)

In [59]:
df['customer_age_group'].unique()

array(['45–54', '18–24', '55+', '35–44', '25–34'], dtype=object)

In [60]:
df['previous_device_os'].unique()

array([nan, 'iOS 16', 'New User', 'Other', 'iOS 15', 'Android', 'iOS 17'],
      dtype=object)

In [61]:
df['previous_device_os'].isna().mean()

np.float64(0.7005217391304348)

In [62]:
df['previous_device_os'].fillna('No Previous Device',inplace=True)

C:\Users\Majid Mokhtar\AppData\Local\Temp\ipykernel_12428\983133987.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['previous_device_os'].fillna('No Previous Device',inplace=True)

In [63]:
df['previous_device_os'].unique()

array(['No Previous Device', 'iOS 16', 'New User', 'Other', 'iOS 15',
       'Android', 'iOS 17'], dtype=object)

## Sales Quality Columns

In [64]:
df.columns

Index(['sale_id', 'sale_date', 'year', 'quarter', 'month', 'country', 'region',
       'city', 'product_name', 'category', 'storage', 'color',
       'unit_price_usd', 'discount_pct', 'units_sold', 'discounted_price_usd',
       'revenue_usd', 'currency', 'fx_rate_to_usd', 'revenue_local_currency',
       'sales_channel', 'payment_method', 'customer_segment',
       'customer_age_group', 'previous_device_os', 'customer_rating',
       'return_status'],
      dtype='object')

In [65]:
df['customer_rating'].unique()

array([4.1, 4.8, 4.3, nan, 4.9, 3.6, 4.7, 4.4, 3.4, 4.5, 3.9, 4.6, 3.7,
       3.8, 3.1, 5. , 4. , 3.5, 3.3, 4.2, 3.2, 3. ])

In [66]:
df['customer_rating'].isna().sum()

np.int64(3360)

In [67]:
df['customer_rating'].isna().mean()

np.float64(0.2921739130434783)

In [68]:
df['customer_rating'].dtype

dtype('float64')

In [69]:
df.insert(26,'has_rating',df['customer_rating'].notna())

In [70]:
df['customer_rating'] = df['customer_rating'].fillna(0)

In [71]:
df['customer_rating'].unique()

array([4.1, 4.8, 4.3, 0. , 4.9, 3.6, 4.7, 4.4, 3.4, 4.5, 3.9, 4.6, 3.7,
       3.8, 3.1, 5. , 4. , 3.5, 3.3, 4.2, 3.2, 3. ])

In [72]:
df['return_status'].unique()

array(['Kept', 'Exchanged', 'Returned'], dtype=object)

## Saving File

In [73]:
df1 = df.to_csv('../Data/Clean Data/apple_global_sales_cleaned_data.csv')

In [74]:
df

,sale_id,sale_date,year,quarter,month,country,region,city,product_name,category,storage,color,unit_price_usd,discount_pct,units_sold,discounted_price_usd,revenue_usd,currency,fx_rate_to_usd,revenue_local_currency,sales_channel,payment_method,customer_segment,customer_age_group,previous_device_os,customer_rating,has_rating,return_status
0,APPL-00000001,2022-01-03,2022,Q1,January,Argentina,South America,Buenos Aires,AirPods (3rd Gen),AirPods,Not Applicable,Starlight,159.27,7,1,148.12,148.12,ARS,907.0,1.343448e+05,Third-Party Retailer,Cash,Government,45–54,No Previous Device,4.1,True,Kept
1,APPL-00000002,2022-01-04,2022,Q1,January,Argentina,South America,Buenos Aires,USB-C Woven Charge Cable,Accessories,Not Applicable,Black,29.99,15,5,25.49,127.45,ARS,907.0,1.155971e+05,Authorized Reseller,Debit Card,Business,45–54,No Previous Device,4.8,True,Kept
2,APPL-00000003,2022-05-18,2022,Q2,May,Argentina,South America,Buenos Aires,Apple Watch Series 8,Apple Watch,Not Applicable,Titanium,293.92,0,4,293.92,1175.68,ARS,907.0,1.066342e+06,Corporate / B2B,Credit Card,Individual,18–24,No Previous Device,4.3,True,Kept
3,APPL-00000004,2022-05-23,2022,Q2,May,Argentina,South America,Buenos Aires,MacBook Pro 14-inch (M3),Mac,1 TB SSD,Starlight,1932.77,0,2,1932.77,3865.54,ARS,907.0,3.506045e+06,Carrier Store,Credit Card,Education,45–54,No Previous Device,0.0,False,Kept
4,APPL-00000005,2022-07-13,2022,Q3,July,Argentina,South America,Buenos Aires,Apple Watch Ultra 2,Apple Watch,Not Applicable,Midnight,755.44,5,3,717.67,2153.01,ARS,907.0,1.952780e+06,Apple Store,Net Banking,Education,18–24,No Previous Device,0.0,False,Kept
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11495,APPL-00011496,2024-02-08,2024,Q1,February,Vietnam,Asia,Nha Trang,Apple Watch Series 9,Apple Watch,Not Applicable,Natural,420.53,5,2,399.50,799.00,VND,24500.0,1.957550e+07,Third-Party Retailer,Gift Card,Individual,18–24,No Previous Device,4.0,True,Kept
11496,APPL-00011497,2024-02-15,2024,Q1,February,Vietnam,Asia,Nha Trang,Mac Pro (M2 Ultra),Mac,256 GB SSD,Midnight,7302.60,7,1,6791.42,6791.42,VND,24500.0,1.663898e+08,Corporate / B2B,Gift Card,Education,45–54,No Previous Device,4.9,True,Kept
11497,APPL-00011498,2024-08-28,2024,Q3,August,Vietnam,Asia,Nha Trang,iPhone 15,iPhone,128 GB,Deep Purple,759.97,7,5,706.77,3533.85,VND,24500.0,8.657932e+07,Authorized Reseller,Debit Card,Government,35–44,iOS 16,3.8,True,Kept
11498,APPL-00011499,2024-08-31,2024,Q3,August,Vietnam,Asia,Nha Trang,iPhone SE (3rd Gen),iPhone,512 GB,Black,438.99,0,1,438.99,438.99,VND,24500.0,1.075526e+07,Apple Store,EMI / Installment,Education,55+,iOS 17,0.0,False,Kept
11499,APPL-00011500,2024-10-10,2024,Q4,October,Vietnam,Asia,Nha Trang,iPhone 15 Pro Max,iPhone,512 GB,Silver,1271.57,7,1,1182.56,1182.56,VND,24500.0,2.897272e+07,Online (Apple.com),EMI / Installment,Individual,35–44,Other,3.6,True,Kept